import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';

import { join, dirname } from 'path';

const fp = `node_modules/@contentstack/json-rte-serializer/lib/types.d.ts`;
const contentstackJsonRteSerializer = readFileSync(fp).toString();

const interfaceAndTypeRegex = /(interface|type)\s+([A-Za-z0-9_]+)[^{=]*({[^}]*}|=[^;]*;)/g;
let match;
const extractedTypes = {};

while ((match = interfaceAndTypeRegex.exec(contentstackJsonRteSerializer)) !== null) {
  const kind = match[1]; // 'interface' or 'type'
  const name = match[2];
  const body = match[3].trim();
  // For 'type', remove trailing semicolon if present
  extractedTypes[name] = `${kind} ${name} ${body}`.replace(/;\s*$/, '');
}


const outputPath = join('src', 'constants', 'json-rte-serializer.ts');
const outputDir = dirname(outputPath);

// Ensure the output directory exists
if (!existsSync(outputDir)) {
  mkdirSync(outputDir, { recursive: true });
}

// Compose the file content
const header = `// Do not manually edit. This file is auto-generated by scripts/extractTypes.js\n\n`;
const typeDefs = `const TYPE_DEFS = ` + JSON.stringify(extractedTypes, null, 4) + '\n export { TYPE_DEFS };';

writeFileSync(outputPath, header + typeDefs, 'utf8');

